server:
  port: 80

spring:
  thymeleaf:
    cache: false
    check-template-location: false
    content-type: text/html
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  
mybatis:
  configuration:
    default-statement-timeout: 5
    map-underscore-to-camel-case: true
    log-prefix: mybatis.
